### ISSUE TITLE
ImportError: No module named 'wmf.analytics'

### ISSUE THREAD

**Issue by fnielsen** [milimetric/wmf#3]
There is a serious error:

    >>> import wmf3
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named 'wmf3'
    >>> import wmf
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.4/dist-packages/wmf/__init__.py", line 1, in <module>
        from wmf.analytics.api import PageviewsClient
    ImportError: No module named 'wmf.analytics'

I believe the PR of @whym (https://github.com/milimetric/wmf/pull/2) fixes this issue.

**Comment by milimetric** [comment]
Thank you very much, I pushed a new version so a `pip install --upgrade wmf` should fix it.

**Comment by fnielsen** [comment]
Thanks. That did it.
